version: '3.9'

# This is from being deployed on my VPS behind a reverse proxy
networks:
  nginx-front-facing-proxy-network:
    external: true
  localcrimesmap-network:

services:
  localcrimesmap_postgis_db:
    image: postgis/postgis
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: on-failure
    healthcheck:
      test: "exit 0"
    networks:
      - localcrimesmap-network
  
  localcrimesmap_webapp:
    build: .
    command: bash -c "python manage.py collectstatic --no-input && gunicorn localcrimesmap.wsgi:application -b 0.0.0.0:${APP_PORT}"
    restart: on-failure
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DJANGODEBUG=${DJANGODEBUG}
      - SECRETKEY=${SECRETKEY}
    depends_on:
      - localcrimesmap_postgis_db
    networks:
      - nginx-front-facing-proxy-network
      - localcrimesmap-network